(defun ugbib-replace (beg end)
  "org-mode の properties 形式によって記述した bib を bib 形式に変更"
  (interactive "r")
  (goto-char beg)
  (while (re-search-forward "\s*:PROPERTIES:" end t)
    (replace-match "@foo{bar,"))
  (goto-char beg)
  (while (re-search-forward "\s*:END:" end t)
    (replace-match "}")
    (forward-line -1)
    (when (re-search-forward ":\\([^ ]*\\):\\(\s+\\)\\(.*\\)$" end t)
      (replace-match "\\1=\\2{\\3}")))
  (goto-char beg)
  (while (re-search-forward ":\\([^ ]*\\):\\(\s+\\)\\(.*\\)$" end t)
    (replace-match "\\1=\\2{\\3},")))
