(defun rotate-window ()
  (interactive)
  (let* ((wl (reverse (window-list)))
	 (wwl (window-buffer (car wl))))
    (unless (one-window-p)
      (while (not (equal (cdr wl) nil))
	(set-window-buffer (car wl) (window-buffer (nth 1 wl)))
	(setq wl (cdr wl)))
      (set-window-buffer (car wl) wwl)
      (select-window (car wl)))))
